Rectangles/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using RectangleLibrary1.IRectangleGetProperty;
using Rectangles.DataAccess.Repository.IRepository;
using Rectangles.ViewModels;

namespace Rectangles.MVC.Controllers
{
    public class MainController : Controller
    {
            private readonly IRectangleRepository _rectangleRepo;
            private readonly IPointRepository _pointRepo;
            private readonly IColorBodyRepository _colorBodyRepo;
            private readonly IColorLineRepository _colorLineRepo;
            private readonly IRectangleService _rectangleService;


            public MainController(IRectangleRepository rectangleRepo,
                                  IPointRepository pointRepo,
                                  IColorBodyRepository colorBodyRepo,
                                  IColorLineRepository colorLineRepo,
                                  IRectangleService rectangleService)
            {
                _rectangleRepo = rectangleRepo;
                _pointRepo = pointRepo;
                _colorBodyRepo = colorBodyRepo;
                _colorLineRepo = colorLineRepo;
                _rectangleService = rectangleService;
            }



            [HttpGet]
            public async Task<IActionResult> Index()
            {
                return View(await _rectangleService.GetAllRectanglesMethod(_rectangleRepo, _pointRepo,
                                                                           _colorBodyRepo, _colorLineRepo));
            }



            [HttpGet]
            public IActionResult AddRectangle()
            {
                return View();
            }
            
            [HttpPost]
            [IgnoreAntiforgeryToken]
            public async Task<IActionResult> AddRectangle(RectangleViewModel rectangleViewModel)
            {
                if (ModelState.IsValid)
                {
                    await _rectangleService.AddRectanglesMethod(rectangleViewModel, _rectangleRepo, _pointRepo, _colorBodyRepo, _colorLineRepo);
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(rectangleViewModel);
                }
            }



            [HttpGet]
            public async Task<IActionResult> Edit(int? id)
            {
                RectangleViewModel rectangleViewModel = new RectangleViewModel();
                if (id == null)
                {
                    return View(rectangleViewModel);
                }
                else
                {
                    var rectangleViewModelValues = await _rectangleRepo.FindAsync(id.GetValueOrDefault());

                    var botLeftPointValue = await _pointRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.BotLeftId);
                    var topRightPointValue = await _pointRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.TopRightId);
                    var colorBodyValue = await _colorBodyRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.ColorBodyRectangleId);
                    var colorLineValue = await _colorLineRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.ColorLineRectangleId);


                    rectangleViewModel.NumberRectangle = rectangleViewModelValues.NumberRectangle;
                    rectangleViewModel.NameRectangle = rectangleViewModelValues.NameRectangle;
                    rectangleViewModel.BotLeftPointX = botLeftPointValue.XValue;
                    rectangleViewModel.BotLeftPointY = botLeftPointValue.YValue;
                    rectangleViewModel.TopRightPointX = topRightPointValue.XValue;
                    rectangleViewModel.TopRightPointY = topRightPointValue.YValue;
                    rectangleViewModel.ColorBodyRectangle = colorBodyValue.ColorBodyValue;
                    rectangleViewModel.ColorLineRectangle = colorLineValue.ColorLineValue;

                    if (rectangleViewModel == null)
                    {
                        return NotFound();
                    }
                    return View(rectangleViewModel);
                }
            }

            [HttpPost]
            [IgnoreAntiforgeryToken]
            public async Task<IActionResult> Edit(RectangleViewModel rectangleViewModel)
            {
                var rectangleViewModelValues = await _rectangleRepo.FindAsync(rectangleViewModel.Id);

                var botLeftPointValue = await _pointRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.BotLeftId);
                var topRightPointValue = await _pointRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.TopRightId);
                var colorBodyValue = await _colorBodyRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.ColorBodyRectangleId);
                var colorLineValue = await _colorLineRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.ColorLineRectangleId);

                rectangleViewModelValues.Id = rectangleViewModel.Id;
                rectangleViewModelValues.NumberRectangle = rectangleViewModel.NumberRectangle;
                rectangleViewModelValues.NameRectangle = rectangleViewModel.NameRectangle;

                botLeftPointValue.XValue = rectangleViewModel.BotLeftPointX;
                botLeftPointValue.YValue = rectangleViewModel.BotLeftPointY;

                topRightPointValue.XValue = rectangleViewModel.TopRightPointX;
                topRightPointValue.YValue = rectangleViewModel.TopRightPointY;

                colorBodyValue.ColorBodyValue = rectangleViewModel.ColorBodyRectangle;

                colorLineValue.ColorLineValue = rectangleViewModel.ColorLineRectangle;

                if (ModelState.IsValid)
                {
                    _rectangleRepo.Update(rectangleViewModelValues);
                    _pointRepo.Update(botLeftPointValue);
                    _pointRepo.Update(topRightPointValue);
                    _colorBodyRepo.Update(colorBodyValue);
                    _colorLineRepo.Update(colorLineValue);

                    await _rectangleRepo.SaveAsync();
                    await _pointRepo.SaveAsync();
                    await _colorBodyRepo.SaveAsync();
                    await _colorLineRepo.SaveAsync();

                    return RedirectToAction("Index");
                }
                return View(rectangleViewModel);
            }



            [HttpGet]
            public async Task<IActionResult> Delete(int? id)
            {
                RectangleViewModel rectangleViewModel = new RectangleViewModel();
                if (id == null)
                {
                    return View(rectangleViewModel);
                }
                else
                {
                    var rectangleViewModelValues = await _rectangleRepo.FindAsync(id.GetValueOrDefault());

                    var botLeftPointValue = await _pointRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.BotLeftId);
                    var topRightPointValue = await _pointRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.TopRightId);
                    var colorBodyValue = await _colorBodyRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.ColorBodyRectangleId);
                    var colorLineValue = await _colorLineRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.ColorLineRectangleId);

                    rectangleViewModel.Id = rectangleViewModelValues.Id;
                    rectangleViewModel.NumberRectangle = rectangleViewModelValues.NumberRectangle;
                    rectangleViewModel.NameRectangle = rectangleViewModelValues.NameRectangle;
                    rectangleViewModel.BotLeftPointX = botLeftPointValue.XValue;
                    rectangleViewModel.BotLeftPointY = botLeftPointValue.YValue;
                    rectangleViewModel.TopRightPointX = topRightPointValue.XValue;
                    rectangleViewModel.TopRightPointY = topRightPointValue.YValue;
                    rectangleViewModel.ColorBodyRectangle = colorBodyValue.ColorBodyValue;
                    rectangleViewModel.ColorLineRectangle = colorLineValue.ColorLineValue;

                    if (rectangleViewModel == null)
                    {
                        return NotFound();
                    }
                    return View(rectangleViewModel);
                }
            }

            [HttpPost]
            [IgnoreAntiforgeryToken]
            public async Task<IActionResult> Delete(RectangleViewModel rectangleViewModel)
            {
                var rectangleViewModelValues = await _rectangleRepo.FindAsync(rectangleViewModel.Id);
                var botLeftPointValue = await _pointRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.BotLeftId);
                var topRightPointValue = await _pointRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.TopRightId);
                var colorBodyValue = await _colorBodyRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.ColorBodyRectangleId);
                var colorLineValue = await _colorLineRepo.FirstOrDefaultAsync(e => e.Id == rectangleViewModelValues.ColorLineRectangleId);

                if (ModelState.IsValid)
                {
                    _rectangleRepo.Remove(rectangleViewModelValues);
                    _pointRepo.Remove(topRightPointValue);
                    _pointRepo.Remove(botLeftPointValue);
                    _colorBodyRepo.Remove(colorBodyValue);
                    _colorLineRepo.Remove(colorLineValue);

                    await _rectangleRepo.SaveAsync();
                    await _pointRepo.SaveAsync();
                    await _colorBodyRepo.SaveAsync();
                    await _colorBodyRepo.SaveAsync();

                    return RedirectToAction("Index");
                }
                return View(rectangleViewModel);
            }

    }
}

Rectangles/Controllers/RectangleFind1Controller.cs
using Microsoft.AspNetCore.Mvc;
using RectangleLibrary1.IRectangleGetProperty;
using Rectangles.DataAccess.Repository.IRepository;
using Rectangles.ViewModels;

namespace Rectangles.Controllers
{
    public class RectangleFind1Controller : Controller
    {       
        private readonly IRectangleRepository _rectangleRepo;
        private readonly IPointRepository _pointRepo;
        private readonly IColorBodyRepository _colorBodyRepo;
        private readonly IColorLineRepository _colorLineRepo;
        private readonly IRectangleServiceChangingCoordinates _rectangleServiceChangingCoordinates;
        private readonly IRectangleService _rectangleService;
        private readonly IRectangleServiceChangingCoordinatesColorRec _rectangleServiceChangingCoordinatesColorRec;


        public RectangleFind1Controller(IRectangleRepository rectangleRepo, 
                                        IPointRepository pointRepo,
                                        IColorBodyRepository colorBodyRepo,
                                        IColorLineRepository colorLineRepo,
                                        IRectangleServiceChangingCoordinates rectangleServiceChangingCoordinates,
                                        IRectangleService rectangleService,
                                        IRectangleServiceChangingCoordinatesColorRec rectangleServiceChangingCoordinatesColorRec)
        {
            _rectangleRepo = rectangleRepo;
            _pointRepo = pointRepo;
            _colorBodyRepo = colorBodyRepo;
            _colorLineRepo = colorLineRepo;
            _rectangleServiceChangingCoordinates = rectangleServiceChangingCoordinates;
            _rectangleService = rectangleService;
            _rectangleServiceChangingCoordinatesColorRec = rectangleServiceChangingCoordinatesColorRec;
        }



        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return View(await _rectangleService.GetAllRectanglesMethod(_rectangleRepo, _pointRepo,
                                                                       _colorBodyRepo, _colorLineRepo));
        }



        [HttpGet]
        public async Task<IActionResult> IndexChange()
        {
            return View(await _rectangleServiceChangingCoordinates.GetAllRectanglesChangeCoordinateMethod(_rectangleRepo, _pointRepo,
                                                                                                          _colorBodyRepo, _colorLineRepo));
        }



        [HttpGet]
        public async Task<IActionResult> IndexChangeWithNeedDots()
        {
            return View(await _rectangleServiceChangingCoordinates.GetRectanglesWithNeedDotsMethod(_rectangleRepo, _pointRepo,
                                                                                                   _colorBodyRepo, _colorLineRepo));
        }



        [HttpGet]
        public async Task<IActionResult> IndexColor()
        {
            return View(await _rectangleService.GetAllRectanglesMethod(_rectangleRepo, _pointRepo,
                                                                       _colorBodyRepo, _colorLineRepo));
        }



        [HttpGet]
        public async Task<IActionResult> IndexGetColorPink()
        {
            return View(await _rectangleServiceChangingCoordinatesColorRec.GetRectColorChangeCoordinateMethod(_rectangleRepo, 
                                                                                                              _pointRepo,
                                                                                                              _colorBodyRepo, 
                                                                                                              _colorLineRepo));
        }



        [HttpGet]
        public async Task<IActionResult> IndexGetColorPurpleTurquoise()
        {
            return View(await _rectangleServiceChangingCoordinatesColorRec.GetRectColorPurpleTurquoiseMethod(_rectangleRepo,
                                                                                                             _pointRepo,
                                                                                                             _colorBodyRepo,
                                                                                                             _colorLineRepo));
        }
    }
}

Rectangles/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rectangles</title>
    <link rel="stylesheet" href="~/fontawesome/css/all.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

</head>
<body>
    <header class="logo">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-0 textcolorblue">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Main" asp-action="Index">Rectangles
                    <img src="~/Rectangle/Rectangles.JPG" alt="Логотип" class="logo" height="50px">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-lg-start me-5">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item m-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Main" asp-action="">Main Page</a>
                        </li>

                        <li class="nav-item m-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RectangleFind1" asp-action="Index">All Rectangles</a>
                        </li>
                        
                        <li class="nav-item m-1">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RectangleFind1" asp-action="IndexColor">Color Rectangles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        <div class="text-center container">
            &copy; 2023 - Rectangles  <a asp-area="" asp-controller="Main" asp-action=""></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Rectangles/Views/Shared/_RectangleAll.cshtml
@model List<Rectangles.ViewModels.RectangleViewModel>

<div>
   <div class="block-right m-auto">
       <div class="border ml-2">
           <canvas id="canvasDrawing1"></canvas>
       </div>
   </div>   
   
   <div>
       @{
           double[] botLeftX = new double[@Model.Count()];
           double[] botLeftY = new double[@Model.Count()];
           double[] topRightXWidth = new double[@Model.Count()];
           double[] topRightYHight = new double[@Model.Count()];
           string[] colorLineValue = new string[@Model.Count()];
           string[] colorBodyValue = new string[@Model.Count()];
   
       }
   
       @for (int i = 0; i < Model.Count(); i++)
       {
           botLeftX[i] = Model[i].BotLeftPointX;
           botLeftY[i] = Model[i].BotLeftPointY;
           topRightXWidth[i] = Model[i].TopRightPointX - Model[i].BotLeftPointX;
           topRightYHight[i] = Model[i].TopRightPointY - Model[i].BotLeftPointY;
           colorLineValue[i] = Model[i].ColorLineRectangle;
           colorBodyValue[i] = Model[i].ColorBodyRectangle;
       }
   
       @{
           var botLeftXJson = Json.Serialize(botLeftX);
       }
   
       @{
           var botLeftYJson = Json.Serialize(botLeftY);
       }
   
       @{
           var topRightXWidthJson = Json.Serialize(topRightXWidth);
       }
   
       @{
           var topRightYHightJson = Json.Serialize(topRightYHight);
       }
   
       @{
           var colorLineValueJson = Json.Serialize(colorLineValue);
       }
   
       @{
           var colorBodyValueJson = Json.Serialize(colorBodyValue);
       }
   </div>
   <div class="row">
       <div class="col-12">
           <script>
               var canvasId = document.getElementById("canvasDrawing1");
               var ctx = canvasId.getContext('2d');
   
               canvasId.width = 850;
               canvasId.height = 850;
   
               var botLeftXJsons = JSON.parse('@Html.Raw(botLeftXJson)'); //var botLeftXJsons = JSON.parse('@Html.Raw(Json.Serialize(botLeftXJson))');
               var botLeftYJsons = JSON.parse('@Html.Raw(botLeftYJson)');
               var topRightXWidthJsons = JSON.parse('@Html.Raw(topRightXWidthJson)');
               var topRightYHightJsons = JSON.parse('@Html.Raw(topRightYHightJson)');
               var colorLineValueJsons = JSON.parse('@Html.Raw(colorLineValueJson)');
               var colorBodyValueJsons = JSON.parse('@Html.Raw(colorBodyValueJson)');
   
               console.log(botLeftXJsons);
               console.log(botLeftYJsons);
               console.log(topRightXWidthJsons);
               console.log(topRightYHightJsons);
               console.log(colorLineValueJsons);
               console.log(colorBodyValueJsons);
   
               var j = 0;
               var countRectangles = 1;
   
               botLeftXJsons.forEach((item) => {
                   if (countRectangles <= 5) {
                       ctx.beginPath();
                       ctx.rect(botLeftXJsons[j], botLeftYJsons[j], topRightXWidthJsons[j], topRightYHightJsons[j]);
                       ctx.closePath();
                       ctx.strokeStyle = "black"; //цвет линии
                       ctx.fillStyle = "rgba(64, 224, 208, 0.5)"; //0.5 - прозрачность
                       ctx.fill();
                       ctx.lineWidth = 3;
                       ctx.stroke();
   
                       console.log(ctx.strokeStyle);
                   }
                   else {
                       ctx.beginPath();
                       ctx.rect(botLeftXJsons[j], botLeftYJsons[j], topRightXWidthJsons[j], topRightYHightJsons[j]);
                       ctx.closePath();
                       ctx.strokeStyle = "brown"; //цвет линии
                       ctx.lineWidth = 11;
                       ctx.stroke();
                       }
                       j++;
                       countRectangles++;
               });
           </script>
       </div>    
   </div>
</div>
     

Rectangles/Views/Shared/_RectangleAllColor.cshtml
@model List<Rectangles.ViewModels.RectangleViewModel>

<div>
   <br />
   <br />
   <h3 class="text-center p-xl-2">Rectangles layout</h3>
   <br />
   <div class="block-right m-auto">
       <div class="border ml-2">
           <canvas id="canvasDrawing1"></canvas>
       </div>
   </div>   
   
   <div>
       @{
           double[] botLeftX = new double[@Model.Count()];
           double[] botLeftY = new double[@Model.Count()];
           double[] topRightXWidth = new double[@Model.Count()];
           double[] topRightYHight = new double[@Model.Count()];
           string[] colorLineValue = new string[@Model.Count()];
           string[] colorBodyValue = new string[@Model.Count()];
   
       }
   
       @for (int i = 0; i < Model.Count(); i++)
       {
           botLeftX[i] = Model[i].BotLeftPointX;
           botLeftY[i] = Model[i].BotLeftPointY;
           topRightXWidth[i] = Model[i].TopRightPointX - Model[i].BotLeftPointX;
           topRightYHight[i] = Model[i].TopRightPointY - Model[i].BotLeftPointY;
           colorLineValue[i] = Model[i].ColorLineRectangle;
           colorBodyValue[i] = Model[i].ColorBodyRectangle;
       }
   
       @{
           var botLeftXJson = Json.Serialize(botLeftX);
       }
   
       @{
           var botLeftYJson = Json.Serialize(botLeftY);
       }
   
       @{
           var topRightXWidthJson = Json.Serialize(topRightXWidth);
       }
   
       @{
           var topRightYHightJson = Json.Serialize(topRightYHight);
       }
   
       @{
           var colorLineValueJson = Json.Serialize(colorLineValue);
       }
   
        @{
            var colorBodyValueJson = Json.Serialize(colorBodyValue);
        }


       @{
            var colorTurquoise = RectangleLibrary1.RectangleServiceConstants.RectangleColorBodyEqTurquoise;
       }
        @{
            var colorPurple = RectangleLibrary1.RectangleServiceConstants.RectangleColorBodyEqPurple;
       }
        @{
            var colorPink = RectangleLibrary1.RectangleServiceConstants.RectangleColorBodyEqPink;
        }


   </div>
   <div class="row">
       <div class="col-12">
           <script>
               var canvasId = document.getElementById("canvasDrawing1");
               var ctx = canvasId.getContext('2d');
   
               canvasId.width = 850;
               canvasId.height = 850;
   
               var botLeftXJsons = JSON.parse('@Html.Raw(botLeftXJson)'); //var botLeftXJsons = JSON.parse('@Html.Raw(Json.Serialize(botLeftXJson))');
               var botLeftYJsons = JSON.parse('@Html.Raw(botLeftYJson)');
               var topRightXWidthJsons = JSON.parse('@Html.Raw(topRightXWidthJson)');
               var topRightYHightJsons = JSON.parse('@Html.Raw(topRightYHightJson)');
               var colorLineValueJsons = JSON.parse('@Html.Raw(colorLineValueJson)');
               var colorBodyValueJsons = JSON.parse('@Html.Raw(colorBodyValueJson)');
   
               console.log(botLeftXJsons);
               console.log(botLeftYJsons);
               console.log(topRightXWidthJsons);
               console.log(topRightYHightJsons);
               console.log(colorLineValueJsons);
               console.log(colorBodyValueJsons);
   
               var j = 0;
               var countRectangles = 1;

   
               botLeftXJsons.forEach((item) => {
                   if (countRectangles <= 5) {
                       ctx.beginPath();
                       ctx.rect(botLeftXJsons[j], botLeftYJsons[j], topRightXWidthJsons[j], topRightYHightJsons[j]);
                       ctx.closePath();
                       ctx.strokeStyle = "black"; //цвет линии

                        console.log(colorBodyValueJsons[j]);

                       if (colorBodyValueJsons[j] == "@colorTurquoise") 
                       {
                           ctx.fillStyle = "rgba(0, 128, 128, 0.87)"; //0.87 - прозрачность
                       }
                        if (colorBodyValueJsons[j] == "@colorPurple") {
                            ctx.fillStyle = "rgba(128, 0, 128, 0.87)"; //0.87 - прозрачность
                       }
                        if (colorBodyValueJsons[j] == "@colorPink") 
                        {
                            ctx.fillStyle = "rgba(255, 192, 203, 0.87)"; //0.87 - прозрачность
                        }
                       
                       ctx.fill();
                       ctx.lineWidth = 3;
                       ctx.stroke();
   
                       console.log(ctx.strokeStyle);
                   }
                   else {
                       ctx.beginPath();
                       ctx.rect(botLeftXJsons[j], botLeftYJsons[j], topRightXWidthJsons[j], topRightYHightJsons[j]);
                       ctx.closePath();
                       ctx.strokeStyle = "brown"; //цвет линии
                       ctx.lineWidth = 11;
                       ctx.stroke();
                       }
                       j++;
                       countRectangles++;
               });
           </script>
       </div>    
   </div>
</div>
     